// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1781818276);
user_pref("app.update.lastUpdateTime.background-update-timer", 1781818276);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1781818276);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1781818245);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.startup.homepage_override.buildID", "20260414220523");
user_pref("browser.startup.homepage_override.mstone", "140.10.0");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.lastAppBuildId", "20260522150903");
user_pref("extensions.lastAppVersion", "9.0.4");
user_pref("extensions.lastPlatformVersion", "140.10.0");
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.zotero.automaticSnapshots", false);
user_pref("extensions.zotero.baseAttachmentPath", "/home/achalmaedison/Documents/biblioteca");
user_pref("extensions.zotero.dataDir", "/home/achalmaedison/Zotero");
user_pref("extensions.zotero.export.quickCopy.locale", "es-MX");
user_pref("extensions.zotero.export.quickCopy.setting", "bibliography=http://www.zotero.org/styles/apa");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.lastSelectedPrefPane", "zotero-prefpane-advanced");
user_pref("extensions.zotero.lastViewedFolder", "C137");
user_pref("extensions.zotero.openNoteInNewWindow", true);
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"false\",\"width\":\"240px\"},\"zotero-collections-pane\":{\"width\":\"457\"},\"zotero-collections-splitter\":{\"state\":\"\"},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-splitter\":{\"state\":\"\",\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"507\",\"height\":\"205\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-splitter-stacked\":{\"state\":\"collapsed\"}}");
user_pref("extensions.zotero.panes.abstract.open", true);
user_pref("extensions.zotero.panes.attachment-annotations.open", true);
user_pref("extensions.zotero.panes.attachment-info.open", true);
user_pref("extensions.zotero.panes.attachments.open", true);
user_pref("extensions.zotero.panes.context-all-notes.open", true);
user_pref("extensions.zotero.panes.context-item-notes.open", true);
user_pref("extensions.zotero.panes.info.open", true);
user_pref("extensions.zotero.panes.libraries-collections.open", true);
user_pref("extensions.zotero.panes.note-info.open", true);
user_pref("extensions.zotero.panes.notes.open", true);
user_pref("extensions.zotero.panes.related.open", true);
user_pref("extensions.zotero.panes.tags.open", true);
user_pref("extensions.zotero.postUpgradeBannerVersionShown", 9);
user_pref("extensions.zotero.prefVersion", 22);
user_pref("extensions.zotero.saveRelativeAttachmentPath", true);
user_pref("extensions.zotero.sidebarState", "{\"library\":{\"width\":240,\"open\":false},\"reader\":{\"width\":240,\"open\":true}}");
user_pref("extensions.zotero.sourceList.persist", "{\"L1\":true,\"C2\":true,\"P1\":false}");
user_pref("extensions.zotero.sync.server.username", "achalmaedison");
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zoteroOpenOfficeIntegration.lastAttemptedVersion", "9.0.0.SOURCE");
user_pref("extensions.zoteroOpenOfficeIntegration.unopkgPaths", "{\"/usr/bin/unopkg\":true,\"/usr/lib/libreoffice/program/unopkg\":true}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1781818755);
user_pref("intl.accept_languages", "en-US, en");
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1781818755935");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1781818755);
